#!/bin/bash

function runByUsers {
	# $1 is default folder of user
	# $2 is name of user
	cd $1
	autostart="$1/.config/autostart/"
	runuser -l $2 -c "mkdir -p $autostart"
	runuser -l $2 -c "cp -rf /usr/wx-center/wx-center.desktop $autostart"
}

# Get Names of users
cat /etc/passwd | grep '/home/' | grep -v 'cups\|syslog\|mysql\|mongodb' | \
cut -d':' -f1 > /tmp/homes.list

while read USUARIO; do
	runByUsers "/home/$USUARIO" "$USUARIO"
 	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
 	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
 	fi
done < /tmp/homes.list
runByUsers "/etc/skel" "root"